### ISSUE TITLE
Paraview glance + ITK.js

### ISSUE THREAD

**Issue by faustomilletari** [InsightSoftwareConsortium/itk-js#134]
Hello,
I was trying to have images saved to a temporary directory in Paraview Glance, which is based on vue.js 

when I call the function readImageLocalFile or writeImageLocalFile I get the error `Error: Cannot find module '/ImageIOs/itkMetaImageIOJSBinding'`

Is there a way I can solve this?

**Comment by faustomilletari** [comment]
Hello, thanks for your answer. 

I'm trying to develop some changes for glance. Part of my workflow consists of saving/loading datasets to temporary directories on the filesystem. For this reason I wrote this

```
import { mapState } from 'vuex';
import writeImageLocalFile from 'itk/writeImageLocalFile';
import readImageLocalFile from 'itk/readImageLocalFile';

export default {
  name: 'TomaatWidgetVolume',
  components: {
    Datasets,
  },
  computed: mapState({
      proxyManager: 'proxyManager',
  }),
  methods: {
    updateList: function () {
      this.datasets = this.proxyManager.getSources();
    },
    chooseSource: function (index) {
      var currentDataset = this.datasets[index]
      console.log(currentDataset.getDataset())
      // not the real thing. just trying out similar to example online
      // real thing would be to write the dataset to disk (not read and write back)
      readImageLocalFile('/tmp/volume1.mha')
        .then((image) => {
          const useCompression = true
          writeImageLocalFile(useCompression, image, '/tmp/volume2.mha')
        })
        .catch((error) => {
          console.error('Error during conversion:\n')
          console.error(error)
        })
    },
  },
  data() {
    return {
      datasets: [],
    };
  },
};
```

**Comment by faustomilletari** [comment]
Hello @floryst,

thanks for your help (also for glance, as I saw that you have answered me). I'm an absolute beginner in JS even though I know ITK/VTK for python and C++. 

The final goal for me is to create a client for TOMAAT (tomaatcloud.github.io) to be able to analyze images with DL approaches (and beyond) from Paraview Glance from Chrome web browser (and similar).

what I am trying to do is to use ITK-js in Paraview Glance. The idea would be to take Glance datasets (VTK) and transform them into ITK images and save them. After they are saved I want to have a plain/text representation of the MHA file which I would like to include in a POST request. POST request to be made multipart with axios. 

All in all it should be similar to this https://github.com/faustomilletari/TOMAAT-Slicer/blob/master/TOMAAT/TOMAAT.py#L366 (where I load the MHA file as plain text) and this https://github.com/faustomilletari/TOMAAT-Slicer/blob/master/TOMAAT/TOMAAT.py#L516 (where I send the POST request to the server).

This project is open source and has no commercial purposes whatsoever. It's a personal project. I have already implemented most of it but I truly have no idea about how I can get a string representing the content of my MHA data. 

I tried to save a dummy ITK image like this:

```
    var mock_image = {
      imageType : {
        dimension: 2,
        componentType: IntTypes.UInt8,
        pixelType: PixelTypes.Scalar,
        components: 1,
      },
      origin: [0, 0],
      spacing: [1, 1],
      direction: [1, 0, 0, 1],
      size: [2, 2],
      data: [0, 1, 2, 3],
    }

    return writeImageArrayBuffer(null, false, mock_image, 'porcodio.png')
    .then(function (writtenArrayBuffer) {
      console.log(writtenArrayBuffer)
    })
```

and I keep getting errors such as 

```
index.js:116 Uncaught (in promise) TypeError: Failed to execute 'postMessage' on 'Worker': Value at index 0 is an untransferable 'undefined' value.
    at eval (index.js:116)
    at new Promise (<anonymous>)
    at Worker.postMessage (index.js:113)
    at eval (writeImageArrayBuffer.js:15)
```

as I said I'm not very experienced with JS and this kind of stuff so I'm struggling quite a bit. If you have any suggestion I would really appreciate it.


Regards,

Fausto

**Comment by faustomilletari** [comment]
In substance the only thing I would need is to be able to select datasets from Paraview glance and obtain a mha compressed file out of them in form of a string (which I need to pass into a http post).

**Comment by faustomilletari** [comment]
I think I am getting closer to the solution. I have written a function to convert the VTK data into ITK and then the hope is to be able to write a ArrayBuffer and interpret it as a string to include into post request. You can find this code here
```
function convertVtkToItkImage(vtkImage) {
  // ItkImage --
  //imageType: The ImageType for this image.
  //origin: An Array with length dimension that describes the location of the center of the lower left pixel in physical units.
  //spacing: An Array with length dimension that describes the spacing between pixel in physical units.
  //-direction: A dimension by dimension Matrix that describes the orientation of the image at its origin. The orientation of each axis are the orthonormal columns.
  //-size: An Array with length dimension that contains the number of pixels along dimension.
  //-data: A TypedArray containing the pixel buffer data.

  // ImageType --
  // dimension: An integer that describes the dimension for the image, typically 2 or 3.
  // pixelType: The PixelType. For example, Scalar, Vector, CovariantVector, or SymmetricSecondRankTensor.
  // componentType: The type of the components in a pixel. This is one of the IntTypes or FloatTypes.
  // components: The number of components in a pixel. For a Scalar pixelType, this will be 1.

  var itkImg = {}

  var scalars = vtkImage.getPointData().getScalars()
  var direction = vtkImage.getDirection()  // are these deep copies?
  var direction_ = vtkImage.getDirection()

  // transposition
  for (let i = 0; i < 3; i++) {
    for (let j = 0; j < 3; j++) {
      direction[i + j * 3] = direction[j + i * 3]
    }
  }

  itkImg['origin'] = vtkImage.getOrigin()
  itkImg['spacing'] = vtkImage.getSpacing()
  itkImg['data'] = scalars.getData()
  itkImg['size'] = vtkImage.getDimensions()
  itkImg['direction'] = direction

  var itkType = {
    dimension: 3, // vtk image is always 3
    pixelType: 1, // 1 == scalar for now...
    componentType: IntTypes.UInt8, // for now...
    components: scalars.getNumberOfComponents(),
  }

  itkImg['imageType'] = itkType

  writeImageArrayBuffer(null, true, itkImg, 'hello.mha')
  .then(function (writtenArrayBuffer) {
    console.log(writtenArrayBuffer)
  })
}
```

unfortunately this code errors (surely because of my ignorance of JS) and I would really appreciate some help. the error is here:

```
"TypeError: Cannot read property 'NaN' of undefined
    at getMatrixElement (http://10.110.21.58:9999/itk/WebWorkers/ImageIO.worker.js:39:64)
    at writeImageEmscriptenFSFile (http://10.110.21.58:9999/itk/WebWorkers/ImageIO.worker.js:63:818)
    at writeImage (http://10.110.21.58:9999/itk/WebWorkers/ImageIO.worker.js:30:3370)
    at http://10.110.21.58:9999/itk/WebWorkers/ImageIO.worker.js:30:4216
    at i (http://10.110.21.58:9999/itk/WebWorkers/ImageIO.worker.js:2:2049)
    at o (http://10.110.21.58:9999/itk/WebWorkers/ImageIO.worker.js:2:1874)
    at http://10.110.21.58:9999/itk/WebWorkers/ImageIO.worker.js:2:2423"
```

Regards,

**Comment by faustomilletari** [comment]
Hello, I think I have been able to write a function to transform VTK images back to ITK images and save them to ArrayBuffer.

```
function convertVtkToItkImage(vtkImage) {
  var scalars = vtkImage.getPointData().getScalars()
  var direction = vtkImage.getDirection()

  let type = new ImageType(3, IntTypes.UInt8, 1, scalars.getNumberOfComponents())

  let image = new Image(type)

  // transposition
  for (let i = 0; i < 3; i++) {
    for (let j = 0; j < 3; j++) {
      image.direction.data[i + j * 3] = direction[j + i * 3]
    }
  }

  image.origin = vtkImage.getOrigin()
  image.spacing = vtkImage.getSpacing()
  image.data = scalars.getData()
  image.size = vtkImage.getDimensions()

  var writtenArrayBuffer = writeImageArrayBuffer(null, true, image, 'image.mha')
}
```
now the missing piece is to be able to get a string out of what I have just written. Do you have some ideas about how to do it? 

Regards,

**Comment by faustomilletari** [comment]
As this thread is closely related with Paraview, the discussion will follow here: https://github.com/Kitware/paraview-glance/issues/180#issuecomment-408853685
