### ISSUE TITLE
itk::MemoryAllocationError if loading two times the same image in different function scope

### ISSUE THREAD

**Issue by vampolo** [InsightSoftwareConsortium/itk-js#367]
Hi,

I have a code similar to

```
const readImageLocalDICOMFileSeries = require('itk/readImageLocalDICOMFileSeries');


//requiring path and fs modules
const path = require('path');
const fs = require('fs');

const readPath = (directoryPath) => {
//passsing directoryPath and callback function
  const files = fs.readdirSync(directoryPath);
  return files.map(x => path.join(directoryPath, x));

}

module.exports = async function (fastify, opts) {
  fastify.get('/api/test', async function (request, reply) {
    const files = readPath('../data/dicomCases/DICOM2');
    console.log('files', files);
    const image = await readImageLocalDICOMFileSeries(files);
    console.log('image', image);
    
    return { root: true }
  })
}
```

This is being executed in Node.js. First execution goes fine, but as soon as i execute the same function the second time i get this error:

```
Exception thrown while writing the image

itk::MemoryAllocationError (0x694cf8)
Location: "unknown"
File: /ITK/Modules/Core/Common/include/itkImportImageContainer.hxx
Line: 192
Description: Failed to allocate memory for image.


18:25:26 🚨 Could not read series GET 500 /api/test
Error: Could not read series
    at readImageEmscriptenFSDICOMFileSeries (/Users/vampolo/test/vtk-viewer/server/node_modules/itk/readImageEmscriptenFSDICOMFileSeries.js:42:11)
    at /Users/vampolo/test/vtk-viewer/server/node_modules/itk/readImageLocalDICOMFileSeries.js:29:19
    at new Promise (<anonymous>)
    at readImageLocalDICOMFileSeries (/Users/vampolo/test/vtk-viewer/server/node_modules/itk/readImageLocalDICOMFileSeries.js:17:10)
    at Object.<anonymous> (/Users/vampolo/test/vtk-viewer/server/routes/root.js:20:25)
    at preHandlerCallback (/Users/vampolo/test/vtk-viewer/server/node_modules/fastify/lib/handleRequest.js:120:28)
    at preValidationCallback (/Users/vampolo/test/vtk-viewer/server/node_modules/fastify/lib/handleRequest.js:103:5)
    at handler (/Users/vampolo/test/vtk-viewer/server/node_modules/fastify/lib/handleRequest.js:69:5)
    at handleRequest (/Users/vampolo/test/vtk-viewer/server/node_modules/fastify/lib/handleRequest.js:18:5)
    at runPreParsing (/Users/vampolo/test/vtk-viewer/server/node_modules/fastify/lib/route.js:385:5)
{
[...]
```

Another error i see is the following:

```
11:32:40 🚨 FS error GET 500 /api/test
Error
    at Object.ensureErrnoError (/Users/vampolo/test/vtk-viewer/server/node_modules/itk/ImageIOs/itkDICOMImageSeriesReaderJSBinding.js:1:1777303)
    at Object.staticInit (/Users/vampolo/test/vtk-viewer/server/node_modules/itk/ImageIOs/itkDICOMImageSeriesReaderJSBinding.js:1:1777523)
    at Object.<anonymous> (/Users/vampolo/test/vtk-viewer/server/node_modules/itk/ImageIOs/itkDICOMImageSeriesReaderJSBinding.js:1:1872467)
    at Module._compile (internal/modules/cjs/loader.js:1075:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
    at Module.load (internal/modules/cjs/loader.js:940:32)
    at Function.Module._load (internal/modules/cjs/loader.js:781:14)
    at Module.require (internal/modules/cjs/loader.js:964:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at loadEmscriptenModuleNode (/Users/vampolo/test/vtk-viewer/server/node_modules/itk/loadEmscriptenModuleNode.js:2:16)
{
  "err": {
    "type": "ErrnoError",
    "message": "FS error",
    "stack": "Error\n    at Object.ensureErrnoError (/Users/vampolo/test/vtk-viewer/server/node_modules/itk/ImageIOs/itkDICOMImageSeriesReaderJSBinding.js:1:1777303)\n    at Object.staticInit (/Users/vampolo/test/vtk-viewer/server/node_modules/itk/ImageIOs/itkDICOMImageSeriesReaderJSBinding.js:1:1777523)\n    at Object.<anonymous> (/Users/vampolo/test/vtk-viewer/server/node_modules/itk/ImageIOs/itkDICOMImageSeriesReaderJSBinding.js:1:1872467)\n    at Module._compile (internal/modules/cjs/loader.js:1075:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:10)\n    at Module.load (internal/modules/cjs/loader.js:940:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:781:14)\n    at Module.require (internal/modules/cjs/loader.js:964:19)\n    at require (internal/modules/cjs/helpers.js:88:18)\n    at loadEmscriptenModuleNode (/Users/vampolo/test/vtk-viewer/server/node_modules/itk/loadEmscriptenModuleNode.js:2:16)",
    "errno": 10
  }
}
11:32:40 ✨ request completed 26ms
```

Which is very strange since the memory allocated for image should go out of scope and be cleared automatically.
Does it requires specific functions to be called to clear internal state for `readimageLocalDICOMFilesSeries`?

**Comment by thewtex** [comment]
Thanks for the report @vampolo 

#374 will clean up used memory.
